### ISSUE TITLE
Idea and Kudos

### ISSUE THREAD

**Issue by ericktheredd** [pamelafox/lscache#15]
No issues here. But wanted to pass along how much I really like this package. Does a great job.

I do have one suggestion, would be nice to be able to have multiple buckets. 

Thank you.

-- Eric

**Comment by peter-gribanov** [comment]
I agree. A multi-basket is an expected feature.
I would like that too.

Now we have to call a `setBucket()` method before call every others methods.

Or you can import the library as a module.

```js
import lscache_lib from 'lscache';

lscache_lib.setBucket('lib');
lscache_lib.set('path', '...', 2);
```

**Comment by pamelafox** [comment]
Disclosure: I have not personally used this library for years, so I don't have the intuition to figure out what's a good feature for it versus what adds unnecessary bloat.  Because of that, I tend to only merge bug fixes, and leave feature-related pull requests open for others to find who are looking for a particular feature.

(I hope one day someone will want to take over as maintainer who actively uses it and has a good idea for what makes sense to add to the API.)

**Comment by pamelafox** [comment]
Since we now have setBucket, I'm closing this issue. Thanks!
